# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()


# Create a 2-dimensional NumPy array using np.array()


# Create a 3-dimensional Numpy array using np.array()


In [3]:
array_1 = np.array([1,3])
array_1

array([1, 3])

In [4]:
array_2 = np.array([[2,3,2], [4,6,7]])
array_2

array([[2, 3, 2],
       [4, 6, 7]])

In [5]:
array_3 = np.array([[[5,7,8], [4,6,3], [2,4,5]], [[5,7,8], [4,6,3], [2,4,5]]])
array_3

array([[[5, 7, 8],
        [4, 6, 3],
        [2, 4, 5]],

       [[5, 7, 8],
        [4, 6, 3],
        [2, 4, 5]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array_1.ndim, type(array_1), array_1.size, array_1.shape, array_1.dtype

(1, numpy.ndarray, 2, (2,), dtype('int32'))

In [7]:
# Attributes of 2-dimensional array
array_2.ndim, type(array_2), array_2.size, array_2.shape

(2, numpy.ndarray, 6, (2, 3))

In [8]:
# Attributes of 3-dimensional array
array_3.ndim, type(array_3), array_3.size, array_3.shape

(3, numpy.ndarray, 18, (2, 3, 3))

In [9]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(array_2)
df

0  1  2
0  2  3  2
1  4  6  7

In [10]:
# Create an array of shape (10, 2) with only ones
array_ones = np.ones((10,2))
array_ones.shape

(10, 2)

In [11]:
# Create an array of shape (7, 2, 3) of only zeros
array_zeros = np.zeros((7,3,2))
array_zeros.shape

(7, 3, 2)

In [12]:
# Create an array within a range of 0 and 100 with step 3
random_array = np.arange(0,100,3)
random_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [13]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array_1 = np.random.randint(0,10, size=(7,2))
random_array_1

array([[3, 5],
       [7, 7],
       [6, 8],
       [5, 6],
       [4, 7],
       [3, 8],
       [6, 8]])

In [14]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_3 = np.random.random((3,5))
random_array_3

array([[0.19642987, 0.97111874, 0.57123759, 0.98170568, 0.29830865],
       [0.11261032, 0.23157101, 0.02359281, 0.18336543, 0.47770754],
       [0.38270996, 0.64238015, 0.39139243, 0.82152619, 0.69726104]])

In [15]:
# Set the random seed to 42
random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_seed = np.random.randint(0,10, size=(4,6))
random_array_seed

NameError: name 'random' is not defined

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [ ]:
random_array_seed

In [ ]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_4 = np.random.randint(1,10, size=(3,7))
random_array_4
# Find the unique numbers in the array you just created
np.unique(random_array_4)

In [ ]:
# Find the 0'th index of the latest array you created
random_array_4

In [ ]:
random_array_4[0][0]

In [ ]:
# Get the first 2 rows of latest array you created
random_array_4[:2]

In [ ]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_4[:2,:2]

In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_5 = np.random.randint(0,10, size=(3,5))
array_ones_1 = np.ones((3,5))

In [ ]:
# Add the two arrays together
addi = random_array_5 + array_ones_1
addi

In [ ]:
# Create another array of ones of shape (5, 3)
array_4 = np.ones((5,3))
array_4

In [ ]:
# Try add the array of ones and the other most recent array together
sum(addi, array_4)

In [ ]:
summation = sum(addi, array_4.T)     #transpose
summation

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [ ]:
# Create another array of ones of shape (3, 5)
array_ones_2 = np.ones((3,5))
array_ones_2

In [ ]:
# Subtract the new array of ones from the other most recent array
sub = summation - array_ones_2
sub

In [ ]:
# Multiply the ones array with the latest array
summation * array_ones_2

In [ ]:
# Take the latest array to the power of 2 using '**'
summation ** 2

In [ ]:
# Do the same thing with np.square()
np.square(summation)

In [ ]:
# Find the mean of the latest array using np.mean()
np.mean(summation)

In [ ]:
# Find the maximum of the latest array using np.max()
np.max(summation)

In [ ]:
# Find the minimum of the latest array using np.min()
np.min(summation)

In [ ]:
# Find the standard deviation of the latest array
np.std(summation)

In [ ]:
# Find the variance of the latest array
np.var(summation)

In [ ]:
# Reshape the latest array to (3, 5, 1)
summation.reshape(3,5,1)

In [ ]:
# Transpose the latest array
summation.T

What does the transpose do?

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_integer_1 = np.random.randint(10, size=(3,3))
random_integer_2 = np.random.randint(10, size=(3,2))
random_integer_1, random_integer_2

In [ ]:
# Perform a dot product on the two newest arrays you created
np.dot(random_integer_1, random_integer_2)

In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_integer_3 = np.random.randint(10, size=(4,3))
random_integer_4 = np.random.randint(10, size=(4,3))
random_integer_3, random_integer_4

In [ ]:
# Perform a dot product on the two newest arrays you created
np.dot(random_integer_3, random_integer_4)

It doesn't work. How would you fix it?

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(random_integer_3.T, random_integer_4)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [17]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random_integers_5 = np.random.randint(10, size=(3,2))
random_integers_6 = np.random.randint(10, size=(3,2))
random_integers_5, random_integers_6

(array([[1, 3],
        [8, 5],
        [6, 5]]),
 array([[3, 7],
        [2, 5],
        [3, 3]]))

In [ ]:
# Compare the two arrays with '>'
random_integers_5 > random_integers_6

What happens when you compare the arrays with `>`?

In [ ]:
# Compare the two arrays with '>='
random_integers_5 >= random_integers_6

In [ ]:
# Find which elements of the first array are greater than 7
random_integers_5 >7

In [18]:
# Which parts of each array are equal? (try using '==')
random_integers_5 == random_integers_6

array([[False, False],
       [False,  True],
       [False, False]])

In [ ]:
# Sort one of the arrays you just created in ascending order
np.sort(random_integers_6)

In [ ]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_integers_6)

In [ ]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_integers_6)

In [ ]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_integers_6)

In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random_integers_6, axis=1)

In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(random_integers_6, axis=0)

In [19]:
# Create an array of normally distributed random numbers
nd_random_numbers = np.random.randn(3,5)
nd_random_numbers

array([[-0.15602423, -1.20498785, -1.11499471, -0.04687605,  0.66838344],
       [-0.75807721,  0.76995726, -0.35617336,  0.73732597,  1.74632927],
       [-0.94825167,  0.25685598,  1.89956576,  0.15357464,  0.66614694]])

In [21]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly_spaced = np.linspace(1,100,10)
evenly_spaced

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.